"""Artifact-QA Mode 3 — 17 artefact x 10 profile = 170 case render matrix.

Spec source: ``.claude/agents/artifact-qa.md`` Mode 3.

Selection
---------
The 17 artefact slugs below are the canonical render set; ``monthly_brag``
is intentionally excluded because it is a legacy duplicate of
``brag_card`` (both map to the same template family but only ``brag_card``
is wired into the unified ``/api/artifacts/generate`` dispatch table).

Workflow per case
-----------------
1. Seed the 10-profile fixture into the isolated SQLite DB.
2. Resolve the artefact service class.
3. Call ``service.generate_for_user(user_id)`` to produce the
   structured payload (or pull from ``services.artifacts.sample_data``
   when the service's generator is unsuitable for synthetic users).
4. Call ``service.render_html(data)`` — must succeed and exceed a
   minimum byte threshold.
5. Call ``service.render_pdf(data)`` when WeasyPrint is installed;
   otherwise the PDF branch is conditionally skipped (the HTML branch
   still asserts).  Generated bytes are written to
   ``tests/artifacts/output/{user_id}/{slug}.pdf``.
6. Optional ``pypdf`` extraction confirms ≥1 page and ≥100 bytes of
   recoverable text.
7. ``_disclaimer.html`` include is assert-checked on every rendered
   HTML (자본시장법 §101 면제 4요건 cross-ref).

Marker
------
All tests carry ``@pytest.mark.artifact_qa`` so the matrix is opt-in:
``pytest -m artifact_qa tests/test_artifact_rendering.py``.

Empty / high-load edge cases
----------------------------
Profile 8 (``new_signup``, portfolio_size=0) and profile 5
(``hyper_diversified``, portfolio_size=75 + 200 trades) are inherently
exercised by the matrix — the per-test assertions branch on
``profile.flags`` to accept empty-state fallbacks (``status='empty'``)
without failing the case.
"""
from __future__ import annotations

import importlib
import os
import re
from pathlib import Path
from typing import Any, Optional

import pytest

from tests.fixtures.virtual_users import USER_PROFILES, profile_ids
from tests.fixtures.sample_data_factory import seed_virtual_user


# ── Matrix definition ─────────────────────────────────────────────────────────

# (slug, module, service class).  Order is alphabetical for stable
# pytest parametrize IDs; the matrix is artefact_slug × profile_label.
ARTIFACT_MATRIX: tuple[tuple[str, str, str], ...] = (
    ("brag_card",             "services.artifacts.brag_card_service",             "BragCardService"),
    ("burn_rate",             "services.artifacts.burn_rate_service",             "BurnRateService"),
    ("capital_allocation",    "services.artifacts.capital_allocation_service",    "CapitalAllocationService"),
    ("credit_rating",         "services.artifacts.credit_rating_service",         "CreditRatingService"),
    ("dd_checklist",          "services.artifacts.dd_checklist_service",          "DDChecklistService"),
    ("dividend_income",       "services.artifacts.dividend_income_service",       "DividendIncomeService"),
    ("earnings_prebrief",     "services.artifacts.earnings_prebrief_service",     "EarningsPreBriefService"),
    ("insider_mirror",        "services.artifacts.insider_mirror_service",        "InsiderMirrorService"),
    ("kpi_dashboard",         "services.artifacts.kpi_dashboard_service",         "KPIDashboardService"),
    ("monthly_finance",       "services.artifacts.monthly_finance_service",       "MonthlyFinanceService"),
    ("portfolio_segment",     "services.artifacts.portfolio_segment_service",     "PortfolioSegmentService"),
    ("quarterly_self_report", "services.artifacts.quarterly_self_report_service", "QuarterlySelfReportService"),
    ("risk_board",            "services.artifacts.risk_board_service",            "RiskBoardService"),
    ("self_audit",            "services.artifacts.self_audit_service",            "SelfAuditService"),
    ("sp500_backtest",        "services.artifacts.sp500_backtest_service",        "SP500BacktestService"),
    ("weekly_memo",           "services.artifacts.weekly_memo_service",           "WeeklyMemoService"),
    ("year_end_letter",       "services.artifacts.year_end_letter_service",       "YearEndLetterService"),
)

assert len(ARTIFACT_MATRIX) == 17, f"Expected 17 artefacts, got {len(ARTIFACT_MATRIX)}"

# Sample-data fallback map — artefacts whose generator requires a
# multi-step interactive flow (capital_allocation, dd_checklist,
# earnings_prebrief, insider_mirror) are fed from
# ``services.artifacts.sample_data`` so the matrix still exercises
# render_html / render_pdf.
SAMPLE_DATA_BUILDERS: dict[str, str] = {
    "capital_allocation":  "sample_capital_allocation",
    "dd_checklist":        "sample_dd_checklist",
    "earnings_prebrief":   "sample_earnings_prebrief",
    "insider_mirror":      "sample_insider_mirror",
    # The remainder all expose a usable ``generate_for_user(user_id)``.
}

_OUTPUT_ROOT = Path(__file__).parent / "artifacts" / "output"
_DISCLAIMER_MARKERS = ("정보 제공 목적", "투자 권유", "투자 판단", "Disclaimer", "면책")

# Naked Korean ticker = 6 digits + ".KS"/".KQ" exposed to the user surface.
# Per feedback_ticker_display.md the hangul display name must be shown
# instead, so a naked ticker in rendered HTML is a display defect.
_NAKED_KR_TICKER = re.compile(r"\d{6}\.(?:KS|KQ)")

# Empty-state copy that an artefact emits when a user has no positions
# (profile #8). Any one of these graceful-fallback phrasings counts.
#
# NOTE: this list was calibrated against the *actual* rendered HTML of the
# 0-position render (not guessed) — services use varied phrasings such as
# "관찰 사항 없음", "기록을 기다립니다", "누적 후 표시", "거래가 없".  The
# disclaimer's "매수·매도·보유" string is deliberately NOT a marker (it would
# match every artefact and hide the real gap).
_EMPTY_STATE_MARKERS = (
    "데이터 부족", "표시할", "아직", "없습니다", "없었습니다",
    "기록을 기다립니다", "관찰 사항 없음", "누적 후 표시",
    "거래가 없", "기록이 없", "보유 종목이 없", "비어 있",
    "no positions", "no data", "no trades", "empty", "0개",
)


def _assert_no_naked_kr_ticker(html: str, slug: str, label: str) -> None:
    """KR-only (#2) / international (#10) must not leak naked KR tickers.

    We assert against the full rendered HTML and treat any naked ticker as
    a display regression. This is deliberately strict so display bugs
    surface for CEO triage.
    """
    hits = sorted(set(m.group(0) for m in _NAKED_KR_TICKER.finditer(html)))
    if hits:
        pytest.fail(
            f"Naked KR ticker leaked to rendered HTML for {slug} × {label}: "
            f"{hits[:5]} (expected hangul display name per feedback_ticker_display)"
        )


def _assert_empty_state_copy(html: str, slug: str, label: str) -> None:
    """new_signup (#8) artefacts that still render HTML must show fallback copy."""
    low = html.lower()
    if not any(m.lower() in low for m in _EMPTY_STATE_MARKERS):
        pytest.fail(
            f"new_signup empty-state copy missing for {slug} × {label} "
            f"(expected one of {_EMPTY_STATE_MARKERS[:4]}…)"
        )


# ── Optional deps — handled gracefully so unit run doesn't require them ──────

def _try_pypdf():
    try:
        from pypdf import PdfReader  # type: ignore
        return PdfReader
    except Exception:
        return None


def _weasyprint_available() -> bool:
    try:
        from weasyprint import HTML  # noqa: F401
        return True
    except Exception:
        return False


# ── Helpers ───────────────────────────────────────────────────────────────────

def _resolve_service(module_path: str, class_name: str):
    """Import + instantiate the artefact service, or skip cleanly."""
    try:
        mod = importlib.import_module(module_path)
    except Exception as exc:
        pytest.skip(f"Service module unimportable: {module_path} ({exc})")
    try:
        klass = getattr(mod, class_name)
    except AttributeError as exc:
        pytest.skip(f"Service class missing: {module_path}.{class_name} ({exc})")
    return klass()


def _build_payload(service: Any, slug: str, user_id: int) -> tuple[Optional[dict], str]:
    """Return (payload, source_tag).  ``source_tag`` ∈ {generate, sample, empty, skip}."""
    builder_name = SAMPLE_DATA_BUILDERS.get(slug)
    if builder_name:
        from services.artifacts import sample_data
        builder = getattr(sample_data, builder_name, None)
        if builder is None:
            return None, "skip"
        return builder(), "sample"

    if not hasattr(service, "generate_for_user"):
        return None, "skip"
    try:
        out = service.generate_for_user(user_id)
    except TypeError:
        # earnings_prebrief takes (user_id, ticker) — handled via sample
        return None, "skip"
    except Exception:
        # Genuine service-level failure: caller may want to assert empty-state.
        return None, "empty"
    if not isinstance(out, dict):
        return None, "empty"
    # Many services return {"status": "empty", ...} for users with no data.
    if out.get("status") == "empty":
        return out, "empty"
    return out, "generate"


def _save_pdf(pdf_bytes: bytes, user_id: int, slug: str) -> Path:
    out_dir = _OUTPUT_ROOT / str(user_id)
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{slug}.pdf"
    out.write_bytes(pdf_bytes)
    return out


def _assert_disclaimer(html: str) -> None:
    """Confirm a §101 disclaimer marker is present.

    Templates include either the Korean phrase, the English "Disclaimer"
    heading, or both via ``_disclaimer.html`` / ``_disclaimer_runner.html``.
    Empty-state HTML (when the service short-circuits) is exempted.
    """
    if not any(marker in html for marker in _DISCLAIMER_MARKERS):
        # Some empty-state HTML legitimately omits the disclaimer.
        if "empty_state" in html.lower() or "no_positions" in html.lower():
            return
        pytest.fail("Rendered HTML missing §101 disclaimer marker")


# ── The matrix test ──────────────────────────────────────────────────────────

@pytest.mark.artifact_qa
@pytest.mark.parametrize("artifact", ARTIFACT_MATRIX, ids=[a[0] for a in ARTIFACT_MATRIX])
@pytest.mark.parametrize("profile", USER_PROFILES, ids=profile_ids())
def test_render_matrix(app, artifact, profile):
    """One case = one (artefact × profile) cell of the 17×10 matrix."""
    slug, module_path, class_name = artifact

    with app.app_context():
        seeded = seed_virtual_user(profile)
        service = _resolve_service(module_path, class_name)
        payload, source = _build_payload(service, slug, seeded.user_id)

    # Empty-state branch: profile #8 (new_signup) is expected here.
    if source == "empty":
        assert "empty_state" in profile.flags or profile.portfolio_size == 0, (
            f"Service returned empty for non-empty profile {profile.label}"
        )
        return

    if payload is None:
        pytest.skip(f"Payload unavailable for {slug} × {profile.label} (source={source})")

    # ── HTML render ─────────────────────────────────────────────────────────
    # Most services expose ``render_html``.  ``earnings_prebrief`` only
    # exposes ``render_pdf_html`` (PDF-page HTML) — accept either rather
    # than silently skipping a real render path.  A service missing *both*
    # is a genuine defect and must surface, not skip.
    html_renderer = (
        getattr(service, "render_html", None)
        or getattr(service, "render_pdf_html", None)
    )
    assert html_renderer is not None, (
        f"{class_name} exposes neither render_html() nor render_pdf_html()"
    )
    html = html_renderer(payload)
    assert isinstance(html, str) and len(html) > 1_000, (
        f"render_html() too small: {len(html) if isinstance(html, str) else 'non-str'}"
    )
    _assert_disclaimer(html)

    # ── Persona-specific content assertions (0원 규칙) ───────────────────────
    # #2 kr_only / #10 international: naked KR ticker must not leak (display
    # bug per feedback_ticker_display — hangul name expected instead).
    if "krw_only" in profile.flags or "multi_currency" in profile.flags:
        _assert_no_naked_kr_ticker(html, slug, profile.label)
    # #8 new_signup: when an artefact renders HTML for a 0-position user it
    # must surface graceful empty-state copy, not a blank/half-broken page.
    if "empty_state" in profile.flags or profile.portfolio_size == 0:
        _assert_empty_state_copy(html, slug, profile.label)

    # ── PDF render (WeasyPrint optional) ────────────────────────────────────
    # When WeasyPrint native deps (libgobject/pango/cairo) are absent the
    # PDF branch cannot run.  This is an *environment* gap, not a passing
    # test — surface it as xfail(strict=False) so it reads distinctly from
    # logic skips and so CI (which installs the deps) actually exercises it.
    if not _weasyprint_available():
        pytest.xfail("weasyprint native deps unavailable — PDF branch not exercised (HTML branch asserted above)")
    if not hasattr(service, "render_pdf"):
        # brag_card uses Playwright PNG, not PDF — exempt.
        return
    pdf_bytes = service.render_pdf(payload)
    if pdf_bytes is None:
        pytest.skip(f"{slug}: render_pdf() returned None (native dep missing)")
    assert isinstance(pdf_bytes, (bytes, bytearray)) and len(pdf_bytes) > 1_000, (
        f"render_pdf() too small: {len(pdf_bytes) if pdf_bytes else 0} bytes"
    )

    saved = _save_pdf(bytes(pdf_bytes), seeded.user_id, slug)
    assert saved.exists() and saved.stat().st_size > 1_000

    # ── pypdf extraction (optional) ─────────────────────────────────────────
    PdfReader = _try_pypdf()
    if PdfReader is None:
        return
    reader = PdfReader(str(saved))
    assert len(reader.pages) >= 1, f"PDF has no pages: {saved}"
    extracted = "".join((p.extract_text() or "") for p in reader.pages)
    # high_load case (profile #5) can render image-only pages; loosen the
    # text threshold there because SVG-only pages legitimately extract empty.
    min_text = 20 if "high_load" in profile.flags else 100
    assert len(extracted) >= min_text, (
        f"PDF text extraction too short ({len(extracted)} chars) for {slug} × {profile.label}"
    )


# ── Edge-case spotlight tests ────────────────────────────────────────────────
# These re-exercise the two extreme profiles outside the parametrize sweep
# so a failure surfaces with a precise name in CI output.

@pytest.mark.artifact_qa
def test_empty_state_fallback(app):
    """Profile #8 (new_signup) must trigger graceful empty-state on weekly_memo."""
    from services.artifacts.weekly_memo_service import WeeklyMemoService
    profile = next(p for p in USER_PROFILES if p.label == "new_signup")
    with app.app_context():
        seeded = seed_virtual_user(profile)
        svc = WeeklyMemoService()
        out = svc.generate_for_user(seeded.user_id)
    assert isinstance(out, dict)
    # weekly_memo_service 의 empty-state 표현은 explicit "status" 필드가 아니라
    # 빈 sector_alloc + 빈 top_movers + None 수익률 + risk_notes 의 "보유 종목 0개"
    # 메시지 조합. 본 wave 작성 시 "status: empty" 필드 존재 가정은 오류.
    # graceful empty-state 의 진짜 시그널: 모든 데이터 컨테이너 empty + risk_notes
    # 에 분산 부족 메시지.
    assert out.get("sector_alloc") == {}, f"Expected empty sector_alloc, got {out.get('sector_alloc')}"
    assert out.get("top_movers_up") == [], f"Expected empty top_movers_up"
    assert out.get("top_movers_down") == [], f"Expected empty top_movers_down"
    assert out.get("weekly_return_pct") is None, "Expected None weekly_return for 0-position user"
    # risk_notes 는 한국어 또는 영어로 "분산 부족" 또는 "0 positions" 등 안내
    risk_notes_text = " ".join(out.get("risk_notes") or [])
    assert ("0개" in risk_notes_text) or ("분산" in risk_notes_text) or ("0 positions" in risk_notes_text.lower()), (
        f"Expected empty-state risk_notes mention, got {risk_notes_text!r}"
    )


@pytest.mark.artifact_qa
def test_high_load_no_oom(app):
    """Profile #5 (hyper_diversified) — 75 positions, 200 trades, no OOM/timeout."""
    from services.artifacts.portfolio_segment_service import PortfolioSegmentService
    profile = next(p for p in USER_PROFILES if p.label == "hyper_diversified")
    with app.app_context():
        seeded = seed_virtual_user(profile)
        svc = PortfolioSegmentService()
        try:
            data = svc.generate_for_user(seeded.user_id)
        except Exception as exc:
            pytest.fail(f"high_load profile crashed generator: {exc}")
    if isinstance(data, dict) and data.get("status") != "empty":
        html = svc.render_html(data)
        assert len(html) > 1_000
