/**
 * PivoxQuant — Report Disclaimer Library
 *
 * 자본시장법 + PIPA + AI 생성 콘텐츠 면책 한/영 양버전.
 *
 * Compliance principles (locked, see CLAUDE.md):
 *   - "AI Assistant" only, NEVER "AI Coach" / "투자 코치"
 *   - POSITIVE / NEGATIVE / NEUTRAL — NEVER BUY / SELL / HOLD
 *   - 추천 / 조언 / recommendation / advice 단어 0건
 *   - DisclaimerBanner already covers screen analytics; this module covers
 *     printable PDF reports where typography + density differ.
 *
 * Mapped 1:1 to /design_handoff_pdf_reports/reports/base.css `.disclaimer`
 * — mono, top hairline, justified.
 */

export type ReportTier = "free" | "pro" | "premium";

export interface ReportDisclaimer {
  /** Common base disclaimer attached to every page footer */
  common: { ko: string; en: string };
  /** Per-report cadence-specific copy */
  cadence: { ko: string; en: string };
  /** Optional backtest / simulation block (#06, #11, #13) */
  backtest?: { ko: string; en: string };
  /** Optional AI-generated content block (every report uses Claude API) */
  ai: { ko: string; en: string };
}

/* ─────────────────── COMMON ─────────────────── */

export const COMMON_DISCLAIMER: ReportDisclaimer["common"] = {
  ko:
    "본 리포트는 PivoxQuant이 공개 데이터와 이용자 보유 종목을 기반으로 자동 생성한 분석 자료이며, " +
    "투자자문, 투자권유, 또는 특정 금융투자상품의 매매를 권유하는 자료가 아닙니다. " +
    "자본시장과 금융투자업에 관한 법률에 따라 PivoxQuant은 투자자문업자 또는 금융투자업자가 아니며, " +
    "본 자료의 내용은 정보 제공 목적에 한정됩니다. " +
    "투자 판단의 최종 책임은 이용자 본인에게 있으며, " +
    "본 자료에 따른 투자 결과로 발생한 손실에 대해 PivoxQuant은 일체의 책임을 지지 않습니다.",
  en:
    "This report is generated automatically by PivoxQuant from public data and the user's declared holdings. " +
    "It is not investment advice, a solicitation, or a recommendation to buy or sell any financial instrument. " +
    "PivoxQuant is not a registered investment adviser or a financial investment business under the " +
    "Korean Financial Investment Services and Capital Markets Act. " +
    "The content is provided for informational purposes only. " +
    "All investment decisions and any resulting losses are the sole responsibility of the user.",
};

/* ─────────────────── AI CONTENT ─────────────────── */

export const AI_DISCLAIMER: ReportDisclaimer["ai"] = {
  ko:
    "본 리포트의 일부 분석 문구는 인공지능(Anthropic Claude) 모델이 생성하였습니다. " +
    "AI 모델은 정확성, 완전성, 적시성을 보장하지 않으며, " +
    "사실 확인은 이용자 본인의 책임입니다.",
  en:
    "Portions of this report are generated by an artificial intelligence model (Anthropic Claude). " +
    "AI output is not guaranteed to be accurate, complete, or current. " +
    "Fact-checking is the user's responsibility.",
};

/* ─────────────────── BACKTEST / SIMULATION ─────────────────── */

export const BACKTEST_DISCLAIMER: ReportDisclaimer["backtest"] = {
  ko:
    "백테스트 결과는 과거 데이터를 기반으로 한 시뮬레이션이며, " +
    "과거의 성과는 미래의 수익을 보장하지 않습니다. " +
    "실제 거래에서는 슬리피지, 수수료, 시장 충격, 유동성 부족 등으로 결과가 상이할 수 있습니다. " +
    "시그널 분류는 POSITIVE / NEGATIVE / NEUTRAL의 중립적 표현이며, 매수/매도 권유가 아닙니다.",
  en:
    "Backtest results are simulations based on historical data; past performance does not guarantee future returns. " +
    "Live results may differ due to slippage, commissions, market impact, and liquidity constraints. " +
    "Signal labels are POSITIVE / NEGATIVE / NEUTRAL — neutral classifications only, not buy or sell recommendations.",
};

/* ─────────────────── CADENCE-SPECIFIC ─────────────────── */

export const CADENCE_DISCLAIMER = {
  weekly: {
    ko:
      "본 주간 리포트는 매주 일요일 한국 시간 기준 직전 거래주를 마감 기준으로 작성됩니다. " +
      "리포트 생성 이후의 시장 변동은 반영되지 않습니다.",
    en:
      "This weekly report is generated each Sunday based on the prior trading week's closing data (KST). " +
      "Market movements after generation are not reflected.",
  },
  daily: {
    ko:
      "본 일일 브리핑은 한국 시간 09:00 KST 직전 야간 시장 데이터를 기준으로 작성됩니다. " +
      "장중 가격 변동은 별도 알림 또는 실시간 피드를 참조하시기 바랍니다.",
    en:
      "This daily brief is generated at 09:00 KST based on overnight session data. " +
      "Intraday price movements should be tracked via alerts or the real-time feed.",
  },
  monthly: {
    ko:
      "본 월간 리포트는 직전 월의 마감 데이터를 기준으로 작성됩니다. " +
      "월중 의사결정 결과는 다음 월 리포트에 반영됩니다.",
    en:
      "This monthly report is generated from the prior calendar month's closing data. " +
      "Mid-month decisions are reflected in the next monthly report.",
  },
  quarterly: {
    ko:
      "본 분기 리포트는 직전 분기 마감 데이터를 기준으로 합니다. " +
      "분석 시점 이후 발생한 사건은 다음 분기 리포트에 반영됩니다.",
    en:
      "This quarterly report is based on the prior quarter's closing data. " +
      "Events occurring after the cutoff are addressed in the next quarter's report.",
  },
  annual: {
    ko:
      "본 연간 레터는 직전 회계연도 전체 거래 활동을 종합하여 작성됩니다. " +
      "세무 신고 자료로 사용 시에는 별도의 공식 거래내역서를 참조하시기 바랍니다.",
    en:
      "This year-end letter aggregates the full prior fiscal year of trading activity. " +
      "For tax filing, please refer to your broker's official transaction statements.",
  },
  event: {
    ko:
      "본 리포트는 특정 이벤트(실적 발표, 컨퍼런스 등) 직전 작성된 사전 분석 자료입니다. " +
      "실제 결과 발표 후 반드시 후속 분석을 통해 가설을 검증하시기 바랍니다.",
    en:
      "This report is a pre-event briefing prepared ahead of an earnings announcement or conference. " +
      "Always validate the hypothesis with a post-event analysis after the actual release.",
  },
  ondemand: {
    ko:
      "본 리포트는 이용자 요청 시점의 데이터를 기준으로 작성된 일회성 분석 자료입니다.",
    en:
      "This is a one-off analysis generated from data available at the time of the user's request.",
  },
} as const;

export type Cadence = keyof typeof CADENCE_DISCLAIMER;

/* ─────────────────── COMPOSITION ─────────────────── */

/**
 * Returns a single composed disclaimer string (ko + en + AI + optional backtest)
 * suitable for placement at the bottom of every report page in the
 * `.pq-pdf-disclaimer` block. Justified, mono, hairline-rule.
 */
export function composeDisclaimer(opts: {
  cadence: Cadence;
  withBacktest?: boolean;
  withAi?: boolean;
}): { ko: string; en: string } {
  const cad = CADENCE_DISCLAIMER[opts.cadence];
  const ko = [
    COMMON_DISCLAIMER.ko,
    cad.ko,
    opts.withAi !== false ? AI_DISCLAIMER.ko : "",
    opts.withBacktest && BACKTEST_DISCLAIMER ? BACKTEST_DISCLAIMER.ko : "",
  ]
    .filter(Boolean)
    .join(" ");
  const en = [
    COMMON_DISCLAIMER.en,
    cad.en,
    opts.withAi !== false ? AI_DISCLAIMER.en : "",
    opts.withBacktest && BACKTEST_DISCLAIMER ? BACKTEST_DISCLAIMER.en : "",
  ]
    .filter(Boolean)
    .join(" ");
  return { ko, en };
}

/* ─────────────────── GOV BLOCK (Pro / Premium) ─────────────────── */

export interface GovernanceMeta {
  preparedBy: string;
  reviewedBy: string;
  methodology: string;
  sources: string;
}

/** Default governance — used when a report doesn't override. Matches the
 *  base.css `.gov-block` four-cell grid (Prepared / Reviewed / Methodology / Sources). */
export const DEFAULT_GOVERNANCE: GovernanceMeta = {
  preparedBy: "PivoxQuant Research Desk · Anthropic Claude (AI Assistant)",
  reviewedBy: "Automated rule checks · No human investment adviser involvement",
  methodology:
    "Public market data, user-declared holdings, and quantitative factor models. " +
    "Signal labels are restricted to POSITIVE / NEGATIVE / NEUTRAL.",
  sources:
    "FMP v4 (price/fundamentals) · KIS read-only (KR holdings) · " +
    "SEC EDGAR · Anthropic Claude (text generation)",
};
