import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - PivoxQuant",
};

export default function TermsPage() {
  return (
    <div className="min-h-[100dvh] bg-white">
      <div className="mx-auto max-w-2xl px-4 py-12 sm:py-20">
        <Link
          href="/login"
          className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 transition-colors mb-8"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
          Back
        </Link>

        <h1 className="text-3xl font-bold tracking-tight text-slate-900">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-slate-500">
          Last updated: April 13, 2026
        </p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-slate-600">
          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              1. Acceptance of Terms
            </h2>
            <p className="mt-3">
              By accessing or using PivoxQuant (&quot;the Service&quot;), you
              agree to be bound by these Terms of Service. If you do not agree,
              please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              2. Description of Service
            </h2>
            <p className="mt-3">
              PivoxQuant is an AI-powered quantitative investment analysis
              platform. The Service provides market data, quantitative signals,
              portfolio analytics, and AI-generated insights for informational
              and educational purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              3. Not Financial Advice
            </h2>
            <p className="mt-3">
              PivoxQuant does not provide personalized investment advice,
              financial planning, or asset management services. All information,
              signals, and analyses are generated by quantitative models
              and AI systems for informational purposes only. You should consult
              a qualified financial advisor before making any investment
              decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              4. User Accounts
            </h2>
            <p className="mt-3">
              You are responsible for maintaining the security of your account
              and all activity that occurs under your account. You must provide
              accurate information when creating your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              5. Acceptable Use
            </h2>
            <p className="mt-3">
              You agree not to misuse the Service. This includes but is not
              limited to: attempting to reverse-engineer the quantitative models,
              scraping data, reselling the Service, or using it for any illegal
              purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              6. Limitation of Liability
            </h2>
            <p className="mt-3">
              PivoxQuant is provided &quot;as is&quot; without warranties of any
              kind. We are not responsible for any investment losses, trading
              decisions, or financial outcomes based on information provided by
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              7. Changes to Terms
            </h2>
            <p className="mt-3">
              We reserve the right to modify these terms at any time. Continued
              use of the Service after changes constitutes acceptance of the new
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">
              8. Contact
            </h2>
            <p className="mt-3">
              For questions about these terms, contact us at{" "}
              <a
                href="mailto:seanbae1521@gmail.com"
                className="text-[var(--sp-accent)] hover:underline"
              >
                seanbae1521@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
