"use client";

import { useState } from "react";
import { ShieldAlert, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

/* ── Disclaimer content per variant ── */

const DISCLAIMER_CONTENT = {
  signal: {
    ko: "본 시그널은 기술적/재무적 데이터를 기반으로 알고리즘이 자동 생성한 분석 결과이며, 특정 종목의 매수 또는 매도를 권유하는 것이 아닙니다. 시그널의 정확성을 보장하지 않으며, 투자 판단은 이용자 본인의 책임입니다.",
    en: "These signals are algorithmically generated based on technical and financial data and do not constitute a recommendation to buy or sell any specific security. Signal accuracy is not guaranteed. All investment decisions are the sole responsibility of the user.",
  },
  "ai-analysis": {
    ko: "AI 분석 결과는 인공지능 모델이 공개 데이터를 기반으로 생성한 참고 자료입니다. 분석 내용의 정확성, 완전성, 적시성을 보장하지 않으며, 이를 유일한 투자 근거로 사용하지 마십시오. 중요한 투자 결정 전에는 공인 투자자문인력 또는 전문가의 조언을 구하시기 바랍니다.",
    en: "AI analysis results are reference materials generated by artificial intelligence models based on publicly available data. We do not guarantee the accuracy, completeness, or timeliness of the analysis. Do not use this as the sole basis for investment decisions. Please consult a licensed investment advisor or financial professional before making significant investment decisions.",
  },
  coaching: {
    ko: "AI 어시스턴트는 이용자의 투자 프로필과 공개 데이터를 기반으로 교육적 목적의 정보를 제공합니다. 이는 개인별 투자자문이 아니며, 특정 금융투자상품의 매매를 권유하지 않습니다. 제공된 의견은 AI 모델의 분석에 기반한 것으로, 투자 전문가의 자문을 대체하지 않습니다.",
    en: "AI assistance provides educational information based on your investment profile and publicly available data. This does not constitute personalized investment advice and does not recommend the purchase or sale of any specific financial investment products. Opinions provided are based on AI model analysis and do not replace professional financial advice.",
  },
  backtest: {
    ko: "백테스트 결과는 과거 데이터를 기반으로 시뮬레이션한 것으로, 과거의 성과가 미래의 수익을 보장하지 않습니다. 실제 거래에서는 슬리피지, 수수료, 시장 충격 등으로 인해 결과가 상이할 수 있습니다.",
    en: "Backtest results are simulations based on historical data. Past performance does not guarantee future returns. Actual trading results may differ due to slippage, commissions, and market impact.",
  },
  // REMOVED 2026-05-10 per legal: "auto-trade" kind retired (autotrader.py 2026-05-05 물리 삭제, 표시광고법 §3 ① 4호 기만광고 회피)
} as const;

const COMMON_DISCLAIMER = {
  ko: "본 서비스는 투자자문이 아니며, 투자 판단의 책임은 이용자에게 있습니다.",
  en: "This service does not constitute investment advice. All investment decisions are your own responsibility.",
};

type DisclaimerType = keyof typeof DISCLAIMER_CONTENT;
type DisclaimerTheme = "dark" | "light";

interface DisclaimerBannerProps {
  type: DisclaimerType;
  /** Force the banner to always stay expanded (used for high-risk variants) */
  alwaysExpanded?: boolean;
  /** Theme — defaults to dark (Vantablack dashboard). Use "light" on ivory feature pages. */
  theme?: DisclaimerTheme;
  className?: string;
}

export function DisclaimerBanner({
  type,
  alwaysExpanded = false,
  theme = "dark",
  className,
}: DisclaimerBannerProps) {
  const [expanded, setExpanded] = useState(true);
  const content = DISCLAIMER_CONTENT[type];

  const isExpanded = alwaysExpanded || expanded;
  const isDark = theme === "dark";

  return (
    <div
      className={cn(
        "rounded-[2px] transition-all duration-300",
        isDark
          ? "border border-[rgba(245,240,232,0.12)] bg-[rgba(255,255,255,0.02)]"
          : "rounded-xl border border-slate-200 bg-slate-50",
        className,
      )}
    >
      <button
        type="button"
        onClick={() => !alwaysExpanded && setExpanded((prev) => !prev)}
        className={cn(
          "flex w-full items-center gap-2 px-3 py-2 text-left",
          !alwaysExpanded && "cursor-pointer",
          alwaysExpanded && "cursor-default",
        )}
        aria-expanded={isExpanded}
        aria-controls="disclaimer-panel"
      >
        <ShieldAlert
          className={cn(
            "h-3.5 w-3.5 shrink-0",
            isDark ? "text-[var(--pq-bronze-light)]" : "text-slate-500",
          )}
        />
        {isDark && (
          <span className="text-pq-kicker tracking-[0.22em] uppercase text-[var(--pq-bronze-light)] mr-1">
            Disclaimer
          </span>
        )}
        <span
          className={cn(
            "flex-1 text-pq-mono-sm font-semibold",
            isDark ? "text-[rgba(245,240,232,0.85)]" : "text-slate-700",
          )}
        >
          {COMMON_DISCLAIMER.ko}
        </span>
        {!alwaysExpanded && (
          <ChevronDown
            className={cn(
              "h-3.5 w-3.5 shrink-0 transition-transform duration-200",
              isDark ? "text-[rgba(245,240,232,0.55)]" : "text-slate-500",
              isExpanded && "rotate-180",
            )}
          />
        )}
      </button>

      {isExpanded && (
        <div
          id="disclaimer-panel"
          role="region"
          className={cn(
            "px-3 pb-3 pt-2 border-t",
            isDark
              ? "border-[var(--pq-ivory-line)]"
              : "border-slate-200",
          )}
        >
          <p
            className={cn(
              "text-pq-mono-sm leading-relaxed",
              isDark ? "text-[rgba(245,240,232,0.75)]" : "text-slate-600",
            )}
          >
            {content.ko}
          </p>
          <p
            className={cn(
              "mt-1.5 text-[10px] leading-relaxed",
              isDark ? "text-[rgba(245,240,232,0.55)]" : "text-slate-500",
            )}
          >
            {content.en}
          </p>
          <p
            className={cn(
              "mt-1.5 text-[10px] leading-relaxed italic",
              isDark ? "text-[rgba(245,240,232,0.45)]" : "text-slate-500",
            )}
          >
            {COMMON_DISCLAIMER.en}
          </p>
        </div>
      )}
    </div>
  );
}
