"use client";

import { useState } from "react";
import { ShieldAlert, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

/* ── Disclaimer content per variant ── */

const DISCLAIMER_CONTENT = {
  signal: {
    ko: "본 시그널은 기술적/재무적 데이터를 기반으로 알고리즘이 자동 생성한 분석 결과이며, 특정 종목의 매수 또는 매도를 권유하는 것이 아닙니다. 시그널의 정확성을 보장하지 않으며, 투자 판단은 이용자 본인의 책임입니다.",
    en: "These signals are algorithmically generated based on technical and financial data and do not constitute a recommendation to buy or sell any specific security. Signal accuracy is not guaranteed. All investment decisions are the sole responsibility of the user.",
  },
  "ai-analysis": {
    ko: "AI 분석 결과는 인공지능 모델이 공개 데이터를 기반으로 생성한 참고 자료입니다(「인공지능 발전과 신뢰 기반 조성 등에 관한 기본법」 제31조에 따른 생성형 AI 표시). 분석 내용의 정확성, 완전성, 적시성을 보장하지 않으며, 이를 유일한 투자 근거로 사용하지 마십시오. 중요한 투자 결정 전에는 공인 투자자문인력 또는 전문가의 조언을 구하시기 바랍니다.",
    en: "AI analysis results are reference materials generated by artificial intelligence models based on publicly available data, and are labeled as AI-generated under Article 31 of the Korean AI Framework Act. We do not guarantee the accuracy, completeness, or timeliness of the analysis. Do not use this as the sole basis for investment decisions. Please consult a licensed investment advisor or financial professional before making significant investment decisions.",
  },
  coaching: {
    ko: "AI 어시스턴트는 이용자의 투자 프로필과 공개 데이터를 기반으로 교육적 목적의 정보를 제공합니다. 이는 개인별 투자자문이 아니며, 특정 금융투자상품의 매매를 권유하지 않습니다. 제공된 의견은 AI 모델의 분석에 기반한 것으로, 투자 전문가의 자문을 대체하지 않습니다.",
    en: "AI assistance provides educational information based on your investment profile and publicly available data. This does not constitute personalized investment advice and does not recommend the purchase or sale of any specific financial investment products. Opinions provided are based on AI model analysis and do not replace professional financial advice.",
  },
  backtest: {
    ko: "백테스트 결과는 과거 데이터를 기반으로 시뮬레이션한 것으로, 과거의 성과가 미래의 수익을 보장하지 않습니다. 실제 거래에서는 슬리피지, 수수료, 시장 충격 등으로 인해 결과가 상이할 수 있습니다.",
    en: "Backtest results are simulations based on historical data. Past performance does not guarantee future returns. Actual trading results may differ due to slippage, commissions, and market impact.",
  },
  // Behavior-Mirror section — factual statistics computed from the user's own
  // trade records (disposition mirror) AND current holdings (concentration
  // mirror). One shared disclaimer covers every mirror on the section, so the
  // wording must stay generic across trade-records + holdings. Explicitly NOT a
  // medical/psychological/mental-health service and NOT a recommendation
  // (legal-confirmed wording 2026-05-30; unified copy 2026-05-30 for N mirrors).
  "behavior-mirror": {
    ko: "본 화면은 귀하의 거래 기록 및 보유 종목에서 산출된 통계를 사실 그대로 표시합니다. 의료기기·심리상담·정신건강 서비스가 아니며, 특정 종목의 매수·매도를 권유하지 않습니다. 투자 판단의 책임은 이용자 본인에게 있습니다.",
    en: "This screen displays factual statistics computed from your own trade records and current holdings. It is not a medical device, psychological service, or mental health service, and does not constitute a recommendation to buy or sell any financial instrument. All investment decisions are your sole responsibility.",
  },
  // REMOVED 2026-05-10 per legal: "auto-trade" kind retired (autotrader.py 2026-05-05 물리 삭제, 표시광고법 §3 ① 4호 기만광고 회피)
} as const;

const COMMON_DISCLAIMER = {
  ko: "본 서비스는 투자자문이 아니며, 투자 판단의 책임은 이용자에게 있습니다.",
  en: "This service does not constitute investment advice. All investment decisions are your own responsibility.",
};

type DisclaimerType = keyof typeof DISCLAIMER_CONTENT;
type DisclaimerTheme = "dark" | "light";

interface DisclaimerBannerProps {
  type: DisclaimerType;
  /** Force the banner to always stay expanded (used for high-risk variants) */
  alwaysExpanded?: boolean;
  /** Theme — defaults to dark (Vantablack dashboard). Use "light" on ivory feature pages. */
  theme?: DisclaimerTheme;
  className?: string;
}

export function DisclaimerBanner({
  type,
  alwaysExpanded = false,
  theme = "dark",
  className,
}: DisclaimerBannerProps) {
  // CEO 2026-05-28: "면책 시각적 별로" — hierarchy uplift.
  //   • Collapsed by default (was expanded) → stately, calmer baseline
  //   • Top hairline accent in bronze-light (dark) / slate (light)
  //   • Playfair "Disclaimer" kicker (was 9px mono kicker, hard to read)
  //   • Primary summary at --pq-text-body-sm (14px) instead of 11px mono
  //   • 18px / 20px row padding (was 8px tight) — breathing room
  //   • Expand body in serif lead with KR/EN explicit subheads
  // Behavior preserved: alwaysExpanded prop, toggle, aria, content keys.
  const [expanded, setExpanded] = useState(false);
  const content = DISCLAIMER_CONTENT[type];

  const isExpanded = alwaysExpanded || expanded;
  const isDark = theme === "dark";

  return (
    <div
      className={cn(
        "rounded-[3px] transition-colors duration-300",
        isDark
          ? "border border-[rgba(245,240,232,0.12)] border-t-[var(--pq-bronze-light)] border-t-[1.5px] bg-[rgba(255,255,255,0.02)]"
          : "rounded-xl border border-slate-200 border-t-slate-400 border-t-[1.5px] bg-slate-50",
        className,
      )}
    >
      <button
        type="button"
        onClick={() => !alwaysExpanded && setExpanded((prev) => !prev)}
        className={cn(
          "flex w-full items-start gap-3 px-5 py-4 text-left md:px-6 md:py-5",
          !alwaysExpanded && "cursor-pointer",
          alwaysExpanded && "cursor-default",
        )}
        aria-expanded={isExpanded}
        aria-controls="disclaimer-panel"
      >
        <ShieldAlert
          className={cn(
            "h-4 w-4 shrink-0 mt-0.5",
            isDark ? "text-[var(--pq-bronze-light)]" : "text-slate-500",
          )}
          aria-hidden="true"
        />
        <div className="flex-1 min-w-0">
          {isDark && (
            <div
              className="font-display"
              style={{
                fontWeight: 500,
                fontSize: "var(--pq-text-h5)",
                lineHeight: 1.2,
                letterSpacing: "0.01em",
                color: "var(--pq-bronze-light)",
                marginBottom: 6,
              }}
            >
              Disclaimer
            </div>
          )}
          <p
            className={cn(
              "leading-relaxed",
              isDark
                ? "text-[rgba(245,240,232,0.88)]"
                : "text-slate-700 font-medium",
            )}
            style={{
              fontSize: "var(--pq-text-body-sm)",
              margin: 0,
            }}
          >
            {COMMON_DISCLAIMER.ko}
          </p>
        </div>
        {!alwaysExpanded && (
          <ChevronDown
            className={cn(
              "h-4 w-4 shrink-0 mt-1 transition-transform duration-200",
              isDark ? "text-[var(--pq-ivory-dim)]" : "text-slate-500",
              isExpanded && "rotate-180",
            )}
            aria-hidden="true"
          />
        )}
      </button>

      {isExpanded && (
        <div
          id="disclaimer-panel"
          role="region"
          className={cn(
            "px-5 pb-5 pt-3 border-t md:px-6 md:pb-6",
            isDark
              ? "border-[var(--pq-ivory-line)]"
              : "border-slate-200",
          )}
        >
          {/* KR detail */}
          <div
            className="font-mono uppercase"
            style={{
              fontSize: "var(--pq-text-eyebrow)",
              letterSpacing: "0.22em",
              color: isDark
                ? "var(--pq-bronze-light)"
                : "rgb(100,116,139)",
              marginBottom: 8,
            }}
          >
            한국어 안내
          </div>
          <p
            className="font-serif"
            style={{
              fontSize: "var(--pq-text-body-sm)",
              lineHeight: 1.65,
              color: isDark ? "rgba(245,240,232,0.78)" : "rgb(71,85,105)",
              margin: 0,
            }}
          >
            {content.ko}
          </p>

          {/* EN detail */}
          <div
            className="font-mono uppercase"
            style={{
              fontSize: "var(--pq-text-eyebrow)",
              letterSpacing: "0.22em",
              color: isDark
                ? "var(--pq-ivory-faint)"
                : "rgb(100,116,139)",
              marginTop: 18,
              marginBottom: 8,
            }}
          >
            English notice
          </div>
          <p
            className="font-serif"
            style={{
              fontSize: "var(--pq-text-body-sm)",
              lineHeight: 1.6,
              color: isDark ? "rgba(245,240,232,0.62)" : "rgb(100,116,139)",
              margin: 0,
            }}
          >
            {content.en}
          </p>
          <p
            className="font-serif"
            style={{
              fontSize: "var(--pq-text-body-sm)",
              lineHeight: 1.6,
              color: isDark ? "rgba(245,240,232,0.55)" : "rgb(100,116,139)",
              margin: "8px 0 0",
            }}
          >
            {COMMON_DISCLAIMER.en}
          </p>
        </div>
      )}
    </div>
  );
}
