import type { Position, Trade } from "./types";

/* Mock portfolio — used while backend positions endpoint isn't wired in. */
export const MOCK_POSITIONS: Position[] = [
  {
    id: "p_aapl",
    symbol: "AAPL",
    name: "Apple Inc.",
    side: "Long",
    shares: 120,
    avgCost: 172.4,
    current: 189.22,
    sector: "Technology",
    purchaseDate: "2025-11-14",
    notes: "Core long-term holding.",
  },
  {
    id: "p_msft",
    symbol: "MSFT",
    name: "Microsoft Corp.",
    side: "Long",
    shares: 60,
    avgCost: 402.8,
    current: 418.55,
    sector: "Technology",
    purchaseDate: "2025-09-02",
  },
  {
    id: "p_nvda",
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    side: "Long",
    shares: 45,
    avgCost: 612.1,
    current: 702.4,
    sector: "Technology",
    purchaseDate: "2026-01-18",
    notes: "Trim on strength above 800.",
  },
  {
    id: "p_googl",
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    side: "Long",
    shares: 90,
    avgCost: 141.7,
    current: 152.13,
    sector: "Communication",
    purchaseDate: "2025-08-22",
  },
  {
    id: "p_meta",
    symbol: "META",
    name: "Meta Platforms Inc.",
    side: "Long",
    shares: 35,
    avgCost: 412.9,
    current: 488.3,
    sector: "Communication",
    purchaseDate: "2025-12-04",
  },
  {
    id: "p_brkb",
    symbol: "BRK.B",
    name: "Berkshire Hathaway",
    side: "Long",
    shares: 30,
    avgCost: 398.4,
    current: 406.12,
    sector: "Financials",
    purchaseDate: "2025-07-10",
  },
  {
    id: "p_jpm",
    symbol: "JPM",
    name: "JPMorgan Chase",
    side: "Long",
    shares: 40,
    avgCost: 182.6,
    current: 195.4,
    sector: "Financials",
    purchaseDate: "2025-10-11",
  },
  {
    id: "p_xom",
    symbol: "XOM",
    name: "Exxon Mobil",
    side: "Long",
    shares: 50,
    avgCost: 118.2,
    current: 112.35,
    sector: "Energy",
    purchaseDate: "2026-02-27",
    notes: "Dividend play.",
  },
];

export const MOCK_TRADES: Trade[] = [
  {
    id: "t1",
    date: "2026-04-18",
    symbol: "NVDA",
    side: "Bought",
    qty: 10,
    price: 698.5,
  },
  {
    id: "t2",
    date: "2026-04-15",
    symbol: "AAPL",
    side: "Bought",
    qty: 20,
    price: 184.1,
  },
  {
    id: "t3",
    date: "2026-04-09",
    symbol: "META",
    side: "Sold",
    qty: 15,
    price: 502.8,
  },
  {
    id: "t4",
    date: "2026-04-03",
    symbol: "XOM",
    side: "Bought",
    qty: 25,
    price: 114.2,
  },
  {
    id: "t5",
    date: "2026-03-28",
    symbol: "JPM",
    side: "Bought",
    qty: 10,
    price: 189.4,
  },
];
