/**
 * API endpoint constants — single source of truth for all backend URLs.
 * Replaces magic strings throughout the frontend.
 */
export const API = {
  auth: {
    register: "/api/auth/register",
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    me: "/api/auth/me",
    google: "/api/auth/google",
  },
  portfolio: {
    list: "/api/portfolio",
    analytics: "/api/portfolio/analytics",
    history: (period: string) => `/api/portfolio/history?period=${period}`,
    addPosition: "/api/portfolio/position",
    editPosition: (id: number) => `/api/portfolio/position/${id}`,
    deletePosition: (id: number) => `/api/portfolio/position/${id}`,
    buyMore: (id: number) => `/api/portfolio/position/${id}/buy`,
    sellShares: (id: number) => `/api/portfolio/position/${id}/sell`,
    buyNew: "/api/portfolio/position/buy-new",
    capital: "/api/portfolio/capital",
  },
  signals: {
    all: "/api/signals",
    one: (ticker: string) => `/api/signals/${ticker}`,
    refresh: "/api/signals/refresh",
    scan: "/api/scan",
  },
  discover: "/api/discover",
  market: {
    overview: "/api/market/overview",
    status: "/api/market/status",
    macro: "/api/macro",
    sectors: "/api/sectors",
    morningBrief: "/api/morning-brief",
    lookup: (ticker: string) => `/api/lookup/${ticker}`,
    prices: "/api/prices",
    chart: (ticker: string) => `/api/chart/${ticker}`,
    earnings: "/api/earnings",
    peers: (ticker: string) => `/api/peers/${ticker}`,
    profile: (ticker: string) => `/api/profile/${ticker}`,
    dividend: (ticker: string) => `/api/dividend/${ticker}`,
    news: (ticker: string) => `/api/news/${ticker}`,
  },
  daytrade: {
    status: "/api/daytrade/status",
    scan: "/api/daytrade/scan",
    analyze: (ticker: string) => `/api/daytrade/analyze/${ticker}`,
    chart: (ticker: string) => `/api/daytrade/chart/${ticker}`,
    prices: "/api/daytrade/prices",
    stream: "/api/daytrade/stream",
  },
  alerts: {
    list: "/api/alerts",
    read: "/api/alerts/read",
    clear: "/api/alerts/clear",
    priceCheck: "/api/alerts/price-check",
  },
  trades: "/api/trades",
  autotrade: {
    status: "/api/autotrade/status",
    start: "/api/autotrade/start",
    stop: "/api/autotrade/stop",
    sellAll: "/api/autotrade/sell-all",
  },
  ai: {
    status: "/api/ai/status",
    chat: "/api/ai/chat",
    swot: "/api/ai/swot",
    competitor: "/api/ai/competitor",
    sectorTrend: "/api/ai/sector-trend",
    commentary: "/api/ai/commentary",
    morningSummary: "/api/ai/morning-summary",
    coaching: "/api/ai/coaching",
  },
  watchlist: {
    list: "/api/watchlist",
    add: "/api/watchlist",
    remove: (id: number) => `/api/watchlist/${id}`,
  },
  realtime: {
    stream: "/api/realtime/stream",
    portfolioStream: "/api/realtime/portfolio-stream",
    price: (ticker: string) => `/api/realtime/price/${ticker}`,
    status: "/api/realtime/status",
  },
  backtest: (ticker: string) => `/api/backtest/${ticker}`,
  quant: {
    vixStrategy: "/api/vix-strategy",
    crossAsset: "/api/cross-asset",
  },
  profile: {
    get: "/api/profile",
    onboarding: "/api/profile/onboarding",
    update: "/api/profile",
    questionnaire: "/api/profile/questionnaire",
  },
} as const;
